config/routes.rb
Lab11App::Application.routes.draw do
  resources :products, except: [ :show ] do
    get 'cancel', on: :member
  end

  root to: "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_ajax

  def set_ajax
    @remote = true
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [ :show, :edit, :update, :destroy ]
  before_action :get_product, only: [ :new ]
  before_action :get_products, only: [ :index, :new, :edit ]

  def index
  end

  def new
    respond_to do |format|
      format.html { render 'index' }
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html { render 'index' }
      format.js
    end
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render 'show', status: :created, location: @product }
        format.js
      else
        format.html { render 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
      format.js
    end
  end

  def cancel
    @product = params[:id] == "0" ? get_product : find_product
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_product
      @product = Product.find(params[:id])
    end

    def get_product
      @product = Product.new released_date: Time.now
    end
    def get_products
      @products = Product.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :model, :released_date, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html

head
  meta charset="utf-8"
  meta name="viewport" content="width=device-width,initial-scale=1.0"
  title= t 'title'
  = stylesheet_link_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tag

body
  = render 'menu'
  = yield
  = render 'footer'

= javascript_include_tag 'application', 'data-turbolinks-track' => true

javascript:

app/views/products/_data_row.html.slim
tr[id="product_#{product.id}"]
  td
    .text-center= product.id
  td
    .text-center= product.name
  td
    .text-center= product.model
  td
    .text-center= l product.released_date, format: :short
  td
    .text-center.img_blowup= link_to image_tag(product.file_url(:small).to_s), product.file_url.to_s, title: product.name, data: { lightbox: "roadtrip" }
  td
    .text-center
      = link_to t('products.edit'), edit_product_path(product), class: 'btn btn-mini', remote: @remote
      '
      = link_to t('products.destroy'), product_path(product), method: :delete, remote: @remote, data: { confirm: t('products.confirm') }, class: 'btn btn-mini btn-danger'

app/views/products/_footer.html.slim
footer
  .container
    .row
      hr
    .row
      .span
      == "&copy;418342" + "&nbsp;"*3 + "Lab 11 CoffeeScript, JavaScript and File Upload"

app/views/products/_form.html.slim
.form-horizontal#form_entry[class=action_name]= form_for @product, remote: @remote do |f|
  .input-prepend.input-append
    .add-on.span= f.label :name
    = f.text_field :name, id: "appendedPrependedInput", class: "span4"
  .input-prepend.input-append
    .span
    .add-on.span1= f.label :released_date
    = f.date_field :released_date, id: "appendedPrependedInput", class: "span3"
  .input-prepend.input-append
    .add-on.span= f.label :model
    = f.text_field :model, id: "appendedPrependedInput", class: "span4"
  .input-prepend.input-append
    .span
    = f.button t('.create'), :class => 'btn btn-success'
    '
    = link_to t('.cancel'), products_path, :class => 'btn btn-warning'

app/views/products/_form_row.html.slim
tr *{ class: "form-horizontal", id: @product.new_record? ? "product_new" : "product_#{@product.id}" }
  td[colspan=6]
    .row
      = form_for @product, multipart: true, remote: @remote do |f|
        .span1
          .text-center= @product.new_record? ? "new" : @product.id
        = f.text_field :name, { style: "width: 19%;" }
        '
        = f.text_field :model, { style: "width: 16%;" }
        '
        = f.date_field :released_date, { style: "width: 19%;" }
        '
        = f.file_field :file, { style: "width: 18%;" }
        '
        span.text-center
          = f.button t(@product.new_record? ? '.create' : '.update'), class: 'btn btn-mini ' + (@product.new_record? ? 'btn-primary' : 'btn-success')
          '
          = link_to t('.cancel'), cancel_product_path(id: @product.new_record? ? 0 : @product.id), remote: @remote, class: 'btn btn-mini btn-warning'

app/views/products/_menu.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
        span.icon-bar
        span.icon-bar
      a.brand[href=products_path]= t 'title'
      .nav-collapse
        ul.nav
          li= link_to "Home", products_path
          li= link_to "About"

app/views/products/edit.html.slim
.page-header
  h1= t '.edit'

= render 'form'

app/views/products/index.html.slim
- model = Product
.container
  .row
    table.table.table-striped.table-condensed
      thead
        tr
          th.span1
            .text-center= model.human_attribute_name(:id)
          th
            .text-center= model.human_attribute_name(:name)
          th
            .text-center= model.human_attribute_name(:model)
          th
            .text-center= model.human_attribute_name(:released_date)
          th
            .text-center= model.human_attribute_name(:image)
          th.span2
            .text-center=t '.actions'
      tbody
        - @products.each do |product|
          - if action_name == 'edit' && product.id == @product.id
            = render 'form_row'
          - else
            = render 'data_row', product: product
        tr#form_entry
        - if action_name == 'new' && defined? @product
          = render 'form_row'
  .row#new_button
    .span2= link_to t('.new'), new_product_path, remote: @remote, class: 'btn btn-primary'